name: CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  code-verification:
    runs-on: ubuntu-latest

   
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
        
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    
      - name: Fix imports order (isort)
        run: isort --profile black .

     
      - name: Fix code formatting (black)
        run: black .

      
      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: autoformat code with black & isort"

      - name: Lint for syntax errors (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-line-length=88 --statistics

      - name: Type checking (mypy)
        run: |
          if [ -n "$(find . -maxdepth 2 -name "*.py" -not -path "*/.*")" ]; then
            mypy --explicit-package-bases --ignore-missing-imports app test
          else
            echo "Python-файлы не найдены. Пропуск проверки типов."
          fi

      - name: Execute Unittests
        run: python -m unittest discover -s . -p "test_*.py"
